apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: bandwidth
spec:
  action: bandwidth
  mode: all
  selector:
    labelSelectors:
       app.kubernetes.io/name: <app-name> 
  bandwidth:
    rate: '1mbps'
    limit: 1000
    buffer: 1000