apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt
spec:
  action: corrupt # the specific chaos action to inject
  mode: all # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector:
    labelSelectors:
       app.kubernetes.io/name: <app-name> # the label of the pod for chaos injection
  corrupt:
    corrupt: '50' # Required, specifies the percentage of packet corruption.
    correlation: '25' # Required
  duration: '5m' # duration for the injected chaos experiment