apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: test-http-chaos
spec:
  mode: all
  selector:
    labelSelectors:
       app.kubernetes.io/name: <app-name>
  target: Request
  port: 443
  method: POST
  request_headers:
    host: <host-path>
  abort: true
  duration: 5m